### ISSUE TITLE
Issues preventing logging to storage grid

### ISSUE THREAD

**Issue by davidreti** [bluedenim/log4j-s3-search#84]
2020-10-16 16:32:01,191 main ERROR Could not create plugin of type class com.van.logging.log4j2.Log4j2Appender for element Log4j2Appender: java.lang.RuntimeException: Cannot build appender due to errors java.lang.RuntimeException: Cannot build appender due to errors

	at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:126)
	at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:24)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:964)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:904)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:896)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:548)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:620)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:637)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.reinitialize(Log4J2LoggingSystem.java:188)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.initialize(Log4J2LoggingSystem.java:144)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:279)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:254)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:219)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:196)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at com.batchexecutor.BatchExecutorApp.main(BatchExecutorApp.java:14)
Caused by: java.lang.IllegalStateException: LoggingEventCache already created. Only one per process.
	at com.van.logging.LoggingEventCache.<init>(LoggingEventCache.java:111)
	at com.van.logging.log4j2.Log4j2AppenderBuilder.build(Log4j2AppenderBuilder.java:121)
	... 29 more

2020-10-16 16:32:01,200 main ERROR Unable to invoke factory method in class com.van.logging.log4j2.Log4j2Appender for element Log4j2Appender: java.lang.IllegalStateException: No factory method found for class com.van.logging.log4j2.Log4j2Appender java.lang.IllegalStateException: No factory method found for class com.van.logging.log4j2.Log4j2Appender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:964)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:904)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:896)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:548)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:620)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:637)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.reinitialize(Log4J2LoggingSystem.java:188)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:72)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:59)
	at org.springframework.boot.logging.log4j2.Log4J2LoggingSystem.initialize(Log4J2LoggingSystem.java:144)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:279)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:254)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:219)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:196)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at com.batchexecutor.BatchExecutorApp.main(BatchExecutorApp.java:14)

2020-10-16 16:32:01,207 main ERROR Null object returned for Log4j2Appender in Appenders.

I also get the following further down in the logs:
`Cannot end publish with com.van.logging.aws.S3PublishHelper@3ce29a4b due to error: org.apache.logging.log4j.core.layout.PatternLayout.serialize(Lorg/apache/logging/log4j/core/LogEvent;Ljava/lang/StringBuilder;)V`

Do you have any ideas?

**Comment by bluedenim** [comment]
The top error is due to the fact that LoggingEventCache is currently a singleton. I do need to fix that to allow multiple instances. Let me do that and see if the other error goes away.

**Comment by bluedenim** [comment]
Release 2.8.2 deployed as a pre-release. This release will remove the singleton restriction on LoggingEventCache.

**Comment by bluedenim** [comment]
Make that 2.8.3.

**Comment by davidreti** [comment]
Thanks! It looks those exceptions are gone. It still doesn't publish though:

Cannot end publish with com.van.logging.aws.S3PublishHelper@2beff664 due to error: org.apache.logging.log4j.core.layout.PatternLayout.serialize(Lorg/apache/logging/log4j/core/LogEvent;Ljava/lang/StringBuilder;)V

Do you know what might be causing this?

**Comment by bluedenim** [comment]
Not without more info. What can help me debug this is:
* copy of your log4j config file
* more of the logs from console (error msgs typically are printed to stderr/stdout since logging them is unreliable when the problem is in the logging flow)
* description of when the problem happens (during shutdown? occasionally? as soon as it tries to publish?)

**Comment by bluedenim** [comment]
Judging from that one line, it looks like it's related to the `PatternLayout ` class, I'm guessing it's coming from https://github.com/bluedenim/log4j-s3-search/blob/master/appender-log4j2/src/main/java/com/van/logging/log4j2/PatternedPathAdjuster.java#L25

Also: can you confirm if you are using Log4j2? In your `log4j2.xml`, what is **s3Path** set to?

**Comment by davidreti** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
	<Properties>
    	<Property name="defaultPatternLayout">%-5p %d{ISO8601} (%t) %30.40c - %m %n</Property>
  	</Properties>

    
	<Appenders>
    	<Console name="Console" target="SYSTEM_OUT">
      		<PatternLayout pattern="${defaultPatternLayout}"/>
    	</Console>
<!--    	<File name="FileAppender" fileName="${sys:logfile_location}/batch-${date:yyyyMMdd_HHmmss_SSS}.log">-->
<!--      		<PatternLayout pattern="${defaultPatternLayout}"/>-->
<!--    	</File>-->
		<Log4j2Appender name="Log4j2Appender">
			<PatternLayout pattern="%d{HH:mm:ss,SSS} [%t] %-5p %c{36} - %m%n"/>
			<verbose>true</verbose>

			<!-- Examples of optional tags to attach to entries (applicable only to SOLR & Elasticsearch)-->
<!--			<tags>TEST,ONE,TWO;THREE</tags>-->

			<!-- Number of messages (lines of log) to buffer before publishing out -->
			<stagingBufferSize>10</stagingBufferSize>
			<!-- Uncomment below to override stagingBufferSize and to attempt a publish every 15 minutes -->
			<stagingBufferAge>1</stagingBufferAge>

			<!-- Uncomment AND configure the lines below to enable upload to S3 -->
			 <s3Bucket>prd-agfmg-sandbox-amp-logs</s3Bucket>
			<!-- Optional config to define the path (key prefix) to use to create custom folder structure under bucket -->
			<!-- If not specified, defaults to writing file(s) directly under bucket -->
			 <s3Path>logs/amp/</s3Path>

<!--			<s3Region>us-east-1</s3Region>-->
			<!-- NOTE: Only s3Region above or (s3ServiceEndpoint + s3SigningRegion) below can be used at one time -->
			<s3ServiceEndpoint>https://sgs3api.<orgname>.com:8082</s3ServiceEndpoint>
<!--			<s3SigningRegion></s3SigningRegion>-->

			<!-- Uncomment below to apply GZIP compression on content sent to S3 -->
			<!--<s3Compression>true</s3Compression>-->

			<!-- Uncomment below to use SSE for S3. NOTE: SSE_S3 is the only supported option right now -->
			<!-- <s3SseKeyType>SSE_S3</s3SseKeyType> -->

			<!-- (Optional) Uncomment to set the pre-configured access control policy to use -->
			<!-- Allowed values: AuthenticatedRead | AwsExecRead | BucketOwnerFullControl | BucketOwnerRead | LogDeliveryWrite | Private | PublicRead | PublicReadWrite -->
			<!-- See: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/CannedAccessControlList.html -->
			<!-- <s3CannedAcl>BucketOwnerFullControl</s3CannedAcl> -->

			<!-- Uncomment AND configure the lines below to enable upload to Azure blob storage -->
			<!-- <azureStorageConnectionString>DefaultEndpointsProtocol=https;AccountName=...;EndpointSuffix=core.windows.net</azureStorageConnectionString> -->
			<!-- <azureBlobContainer>mycontainer</azureBlobContainer> -->
			<!-- <azureBlobNamePrefix>logs/exampleApplication2/</azureBlobNamePrefix> -->

			<!-- Uncomment below to apply GZIP compression on content sent to Azure blob storage -->
			<!-- <azureBlobCompressionEnabled>true</azureBlobCompressionEnabled> -->

			<!-- Uncomment AND configure the lines below to enable upload to Google Cloud Platform's Storage service -->
			<!-- <gcpStorageBucket>mybucket</gcpStorageBucket> -->
			<!-- <gcpStorageBlobNamePrefix>logs/exampleApplication2/</gcpStorageBlobNamePrefix> -->
			<!-- <gcpStorageCompressionEnabled>true</gcpStorageCompressionEnabled> -->

			<!-- Uncomment AND configure the line below to enable upload to SOLR -->
			<!--<solrUrl>http://localhost:8983/solr/gettingstarted/</solrUrl>-->


			<!-- Uncomment AND configure the lines below to enable upload to Elasticsearch -->
			<!--<elasticsearchHosts>localhost:9300</elasticsearchHosts>-->
			<!--<elasticsearchCluster>elasticsearch</elasticsearchCluster>-->
			<!--<elasticsearchIndex>logindex</elasticsearchIndex>-->
			<!--<elasticsearchType>log</elasticsearchType>-->

		</Log4j2Appender>
  	</Appenders>
    
	<Loggers>
		<Root level="WARN">
  			<AppenderRef ref="Console"/>
<!--  			<AppenderRef ref="FileAppender"/>-->
			<AppenderRef ref="Log4j2Appender" />
		</Root>

		<Logger name="org.springframework" level="WARN" additivity="false">
      		<AppenderRef ref="Console"/>
<!--  			<AppenderRef ref="FileAppender"/>-->
			<AppenderRef ref="Log4j2Appender" />
    	</Logger>
		
		<Logger name="org.springframework.jdbc.core.JdbcTemplate" level="DEBUG" additivity="false">
      		<AppenderRef ref="Console"/>
<!--  			<AppenderRef ref="FileAppender"/>-->
			<AppenderRef ref="Log4j2Appender" />
    	</Logger>
		
		<Logger name="org.hibernate" level="WARN" additivity="false">
      		<AppenderRef ref="Console"/>
<!--  			<AppenderRef ref="FileAppender"/>-->
			<AppenderRef ref="Log4j2Appender" />
    	</Logger>

		<Logger name="com.mchange" level="WARN" additivity="false">
      		<AppenderRef ref="Console"/>
<!--  			<AppenderRef ref="FileAppender"/>-->
			<AppenderRef ref="Log4j2Appender" />
    	</Logger>
    </Loggers>
    
</Configuration>
```

I believe it logs that line to stderr every now and then when it tries to publish.

```
"C:\Program Files\Java\jdk1.8.0_191\bin\java.exe" [...]
Console output is saving to: C:\Users\dreti\Desktop\console.txt
Using cache monitor: TimePeriodBasedBufferMonitor(periodInSeconds: 60)
Registering AWS S3 publish helper -> S3 configuration (prd-agfmg-sandbox-amp-logs:logs/amp/ in region null; compressed: false)
INFO  2020-10-21T11:29:47,912 (main) c.common.environment.EnvironmentResolver - Working out client abbreviation... 
Collecting content into C:\Users\dreti\AppData\Local\Temp\1\toBePublished7362240988740775717.tmp before uploading.
INFO  2020-10-21T11:29:48,032 (main) c.common.environment.EnvironmentResolver - Running on WIN 
Cannot end publish with com.van.logging.aws.S3PublishHelper@2beff664 due to error: org.apache.logging.log4j.core.layout.PatternLayout.serialize(Lorg/apache/logging/log4j/core/LogEvent;Ljava/lang/StringBuilder;)V
Using cache monitor: TimePeriodBasedBufferMonitor(periodInSeconds: 60)
Registering AWS S3 publish helper -> S3 configuration (prd-agfmg-sandbox-amp-logs:logs/amp/ in region null; compressed: false)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.6.RELEASE)

INFO  2020-10-21T11:29:53,132 (main) c.common.environment.EnvironmentResolver - Working out client abbreviation... 
INFO  2020-10-21T11:29:53,135 (main) c.common.environment.EnvironmentResolver - Running on WIN 
Collecting content into C:\Users\dreti\AppData\Local\Temp\1\toBePublished4616723031843648222.tmp before uploading.
Cannot end publish with com.van.logging.aws.S3PublishHelper@4102b4a due to error: org.apache.logging.log4j.core.layout.PatternLayout.serialize(Lorg/apache/logging/log4j/core/LogEvent;Ljava/lang/StringBuilder;)V
INFO  2020-10-21T11:29:59,815 (main) ngine.component.memory.MemoryManagerImpl - initialize memory manager 1, bAggressive=false 
[...]
Publish operation is approaching monitor period. Increase period or risk compromising fixed rate.
Cannot end publish with com.van.logging.aws.S3PublishHelper@2beff664 due to error: org.apache.logging.log4j.core.layout.PatternLayout.serialize(Lorg/apache/logging/log4j/core/LogEvent;Ljava/lang/StringBuilder;)V
Collecting content into C:\Users\dreti\AppData\Local\Temp\1\toBePublished7440281146971520617.tmp before uploading.
INFO  2020-10-21T11:30:48,368 (main) ngine.preentity.library.LibraryPreEntity - read classpath in manifest of jar C:\<...>.jar 
[...]
INFO  2020-10-21T11:30:52,502 (MemoryManager-1) ngine.component.memory.MemoryManagerImpl - memory manager thread interrupted 
INFO  2020-10-21T11:30:52,504 (MemoryManager-1) ngine.component.memory.MemoryManagerImpl - Exiting MemoryManager Loop 
Collecting content into C:\Users\dreti\AppData\Local\Temp\1\toBePublished3405899168328500230.tmp before uploading.
Cannot end publish with com.van.logging.aws.S3PublishHelper@4102b4a due to error: org.apache.logging.log4j.core.layout.PatternLayout.serialize(Lorg/apache/logging/log4j/core/LogEvent;Ljava/lang/StringBuilder;)V

Process finished with exit code -1
```

**Comment by bluedenim** [comment]
Great. Let me look into that and repro on my side. Thanks!

**Comment by davidreti** [comment]
Any luck? I managed to publish the logs for the first time finally so it seems this problem resolved itself by refreshing caches/reimporting projects in intelliJ. So not sure how to reproduce it or what was exactly wrong to be honest.

**Comment by bluedenim** [comment]
Ah no; not yet. Got a day job to tend to. :)

I'll look over the weekend.

If it works reliably now, maybe it's not an issue.

**Comment by bluedenim** [comment]
I've tried the log4j2.xml above and was not able to reproduce the error. This is what I have (unused parts omitted):
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
  <Properties>
    <Property name="defaultPatternLayout">%-5p %d{ISO8601} (%t) %30.40c - %m %n</Property>
  </Properties>


  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="${defaultPatternLayout}"/>
    </Console>

    <Log4j2Appender name="Log4j2Appender">
      <PatternLayout pattern="%d{HH:mm:ss,SSS} [%t] %-5p %c{36} - %m%n"/>
      <verbose>true</verbose>

      <!-- Number of messages (lines of log) to buffer before publishing out -->
      <stagingBufferSize>10</stagingBufferSize>
      <!-- Uncomment below to override stagingBufferSize and to attempt a publish every 15 minutes -->
        <stagingBufferAge>5</stagingBufferAge>

      <!-- Uncomment AND configure the lines below to enable upload to S3 -->
      <s3Bucket>...</s3Bucket>
      <!-- Optional config to define the path (key prefix) to use to create custom folder structure under bucket -->
      <!-- If not specified, defaults to writing file(s) directly under bucket -->
      <s3Path>logs/amp/</s3Path>

        <s3Region>us-west-2</s3Region>
        <!-- NOTE: Only s3Region above or (s3ServiceEndpoint + s3SigningRegion) below can be used at one time -->
        <!--<s3ServiceEndpoint>...</s3ServiceEndpoint>-->
        <!--<s3SigningRegion>...</s3SigningRegion>-->

    </Log4j2Appender>
  </Appenders>
  <Loggers>
    <Root level="INFO">
      <AppenderRef ref="ConsoleAppender" />
      <AppenderRef ref="Log4j2Appender" />
    </Root>
  </Loggers>
</Configuration>
```

I shortened the wait time to flush and publish for my example program. I also switched back to **s3Region** instead of using your service endpoint. And I used my own bucket. Seemed to work fine.

Let me know if you see that problem on your side after those refresh/reimport that you did.
